import { Country } from '../types';

export const countries: Country[] = [
  { n: "India", c: "+91" },
  { n: "Afghanistan", c: "+93" },
  { n: "Albania", c: "+355" },
  { n: "Algeria", c: "+213" },
  { n: "Andorra", c: "+376" },
  { n: "Angola", c: "+244" },
  { n: "Argentina", c: "+54" },
  { n: "Armenia", c: "+374" },
  { n: "Australia", c: "+61" },
  { n: "Austria", c: "+43" },
  { n: "Azerbaijan", c: "+994" },
  { n: "Bahrain", c: "+973" },
  { n: "Bangladesh", c: "+880" },
  { n: "Belarus", c: "+375" },
  { n: "Belgium", c: "+32" },
  { n: "Belize", c: "+501" },
  { n: "Benin", c: "+229" },
  { n: "Bhutan", c: "+975" },
  { n: "Bolivia", c: "+591" },
  { n: "Bosnia", c: "+387" },
  { n: "Botswana", c: "+267" },
  { n: "Brazil", c: "+55" },
  { n: "Brunei", c: "+673" },
  { n: "Bulgaria", c: "+359" },
  { n: "Cambodia", c: "+855" },
  { n: "Cameroon", c: "+237" },
  { n: "Canada", c: "+1" },
  { n: "Chile", c: "+56" },
  { n: "China", c: "+86" },
  { n: "Colombia", c: "+57" },
  { n: "Comoros", c: "+269" },
  { n: "Congo", c: "+242" },
  { n: "Costa Rica", c: "+506" },
  { n: "Croatia", c: "+385" },
  { n: "Cuba", c: "+53" },
  { n: "Cyprus", c: "+357" },
  { n: "Czech Republic", c: "+420" },
  { n: "Denmark", c: "+45" },
  { n: "Djibouti", c: "+253" },
  { n: "Dominica", c: "+1767" },
  { n: "Dominican Republic", c: "+1809" },
  { n: "Ecuador", c: "+593" },
  { n: "Egypt", c: "+20" },
  { n: "El Salvador", c: "+503" },
  { n: "Estonia", c: "+372" },
  { n: "Ethiopia", c: "+251" },
  { n: "Fiji", c: "+679" },
  { n: "Finland", c: "+358" },
  { n: "France", c: "+33" },
  { n: "Gabon", c: "+241" },
  { n: "Gambia", c: "+220" },
  { n: "Georgia", c: "+995" },
  { n: "Germany", c: "+49" },
  { n: "Ghana", c: "+233" },
  { n: "Greece", c: "+30" },
  { n: "Grenada", c: "+1473" },
  { n: "Guatemala", c: "+502" },
  { n: "Guinea", c: "+224" },
  { n: "Guyana", c: "+592" },
  { n: "Haiti", c: "+509" },
  { n: "Honduras", c: "+504" },
  { n: "Hong Kong", c: "+852" },
  { n: "Hungary", c: "+36" },
  { n: "Iceland", c: "+354" },
  { n: "Indonesia", c: "+62" },
  { n: "Iran", c: "+98" },
  { n: "Iraq", c: "+964" },
  { n: "Ireland", c: "+353" },
  { n: "Israel", c: "+972" },
  { n: "Italy", c: "+39" },
  { n: "Jamaica", c: "+1876" },
  { n: "Japan", c: "+81" },
  { n: "Jordan", c: "+962" },
  { n: "Kazakhstan", c: "+7" },
  { n: "Kenya", c: "+254" },
  { n: "Kiribati", c: "+686" },
  { n: "Kuwait", c: "+965" },
  { n: "Kyrgyzstan", c: "+996" },
  { n: "Laos", c: "+856" },
  { n: "Latvia", c: "+371" },
  { n: "Lebanon", c: "+961" },
  { n: "Lesotho", c: "+266" },
  { n: "Liberia", c: "+231" },
  { n: "Libya", c: "+218" },
  { n: "Liechtenstein", c: "+423" },
  { n: "Lithuania", c: "+370" },
  { n: "Luxembourg", c: "+352" },
  { n: "Macedonia", c: "+389" },
  { n: "Madagascar", c: "+261" },
  { n: "Malawi", c: "+265" },
  { n: "Malaysia", c: "+60" },
  { n: "Maldives", c: "+960" },
  { n: "Mali", c: "+223" },
  { n: "Malta", c: "+356" },
  { n: "Mauritania", c: "+222" },
  { n: "Mauritius", c: "+230" },
  { n: "Mexico", c: "+52" },
  { n: "Moldova", c: "+373" },
  { n: "Monaco", c: "+377" },
  { n: "Mongolia", c: "+976" },
  { n: "Montenegro", c: "+382" },
  { n: "Morocco", c: "+212" },
  { n: "Mozambique", c: "+258" },
  { n: "Myanmar", c: "+95" },
  { n: "Namibia", c: "+264" },
  { n: "Nauru", c: "+674" },
  { n: "Nepal", c: "+977" },
  { n: "Netherlands", c: "+31" },
  { n: "New Zealand", c: "+64" },
  { n: "Nicaragua", c: "+505" },
  { n: "Niger", c: "+227" },
  { n: "Nigeria", c: "+234" },
  { n: "North Korea", c: "+850" },
  { n: "Norway", c: "+47" },
  { n: "Oman", c: "+968" },
  { n: "Pakistan", c: "+92" },
  { n: "Palau", c: "+680" },
  { n: "Panama", c: "+507" },
  { n: "Papua New Guinea", c: "+675" },
  { n: "Paraguay", c: "+595" },
  { n: "Peru", c: "+51" },
  { n: "Philippines", c: "+63" },
  { n: "Poland", c: "+48" },
  { n: "Portugal", c: "+351" },
  { n: "Qatar", c: "+974" },
  { n: "Romania", c: "+40" },
  { n: "Russia", c: "+7" },
  { n: "Rwanda", c: "+250" },
  { n: "Samoa", c: "+685" },
  { n: "San Marino", c: "+378" },
  { n: "Saudi Arabia", c: "+966" },
  { n: "Senegal", c: "+221" },
  { n: "Serbia", c: "+381" },
  { n: "Seychelles", c: "+248" },
  { n: "Sierra Leone", c: "+232" },
  { n: "Singapore", c: "+65" },
  { n: "Slovakia", c: "+421" },
  { n: "Slovenia", c: "+386" },
  { n: "Solomon Islands", c: "+677" },
  { n: "Somalia", c: "+252" },
  { n: "South Africa", c: "+27" },
  { n: "South Korea", c: "+82" },
  { n: "Spain", c: "+34" },
  { n: "Sri Lanka", c: "+94" },
  { n: "Sudan", c: "+249" },
  { n: "Suriname", c: "+597" },
  { n: "Sweden", c: "+46" },
  { n: "Switzerland", c: "+41" },
  { n: "Syria", c: "+963" },
  { n: "Taiwan", c: "+886" },
  { n: "Tajikistan", c: "+992" },
  { n: "Tanzania", c: "+255" },
  { n: "Thailand", c: "+66" },
  { n: "Togo", c: "+228" },
  { n: "Tonga", c: "+676" },
  { n: "Trinidad & Tobago", c: "+1868" },
  { n: "Tunisia", c: "+216" },
  { n: "Turkey", c: "+90" },
  { n: "Turkmenistan", c: "+993" },
  { n: "Tuvalu", c: "+688" },
  { n: "Uganda", c: "+256" },
  { n: "Ukraine", c: "+380" },
  { n: "UAE", c: "+971" },
  { n: "UK", c: "+44" },
  { n: "USA", c: "+1" },
  { n: "Uruguay", c: "+598" },
  { n: "Uzbekistan", c: "+998" },
  { n: "Vanuatu", c: "+678" },
  { n: "Venezuela", c: "+58" },
  { n: "Vietnam", c: "+84" },
  { n: "Yemen", c: "+967" },
  { n: "Zambia", c: "+260" },
  { n: "Zimbabwe", c: "+263" }
];

export function filterCountries(query: string): Country[] {
  const q = query.toLowerCase().trim();
  if (!q) return countries;
  return countries.filter(
    c => c.n.toLowerCase().includes(q) || c.c.includes(q)
  );
}
